config/routes.rb
Citrusgraph::Application.routes.draw do
  resources :diagrams

  root to: 'diagrams#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/diagram.rb
class Diagram < ActiveRecord::Base
  attr_accessible :legend, :val
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/diagrams_controller.rb
class DiagramsController < ApplicationController
  # GET /diagrams
  # GET /diagrams.json
  def index
    @diagrams = Diagram.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diagrams }
    end
  end

  # GET /diagrams/1
  # GET /diagrams/1.json
  def show
    @diagram = Diagram.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diagram }
    end
  end

  # GET /diagrams/new
  # GET /diagrams/new.json
  def new
    @diagram = Diagram.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diagram }
    end
  end

  # GET /diagrams/1/edit
  def edit
    @diagram = Diagram.find(params[:id])
  end

  # POST /diagrams
  # POST /diagrams.json
  def create
    @diagram = Diagram.new(params[:diagram])

    respond_to do |format|
      if @diagram.save
        format.html { redirect_to @diagram, notice: 'Diagram was successfully created.' }
        format.json { render json: @diagram, status: :created, location: @diagram }
      else
        format.html { render action: "new" }
        format.json { render json: @diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diagrams/1
  # PUT /diagrams/1.json
  def update
    @diagram = Diagram.find(params[:id])

    respond_to do |format|
      if @diagram.update_attributes(params[:diagram])
        format.html { redirect_to @diagram, notice: 'Diagram was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagrams/1
  # DELETE /diagrams/1.json
  def destroy
    @diagram = Diagram.find(params[:id])
    @diagram.destroy

    respond_to do |format|
      format.html { redirect_to diagrams_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagrams_helper.rb
module DiagramsHelper

	def get_total(diagrams)
		n = 0
		diagrams.each do |d|
			n += d.val
		end
		return n
	end

	def get_diagram_url(diagrams,name)
		arr = Array.new
		diagrams.each do |d|
    		arr << d.val
    	end

		Gchart.pie(
			title: name,
        	bg: 'efefef',
			legend: ['yes', 'no', 'i do not know'],
			data: arr)
	end

	def get_diagram_url_pie(diagrams,name)
		total = 0
		res = ''	

		GoogleChart::PieChart.new('320x200', name,false) do |pc| 
			diagrams.each do |d|
	    		pc.data d.legend, d.val
	    	end
		  res = pc.to_url
		  # Pie Chart with no labels 
		  # pc.show_labels = false 
		  # puts "\nPie Chart (with no labels)" 
		  # puts pc.to_url 
		end

		return res
	end

	def get_diagram_url_horbar(diagrams,name)
		res = ''
		arr = Array.new
		arrl = Array.new
		diagrams.each do |d|
    		arr << d.val
    		arrl << d.legend
    	end
		color_1 = 'c53711'
		GoogleChart::BarChart.new("600x200", "Opinion", :horizontal, false) do |bc|
			bc.data name, arr, color_1
			bc.axis :y, :labels => arrl, :font_size => 10
			bc.axis :x, :range => [0,1000]
			bc.show_legend = false
			bc.stacked = true
			bc.data_encoding = :extended
			# bc.shape_marker :circle, :color => '00ff00', :data_set_index => 0, :data_point_index => -1, :pixel_size => 10
			res = bc.to_url
		end
		return res
	end
end

app/views/diagrams/_form.html.erb
<%= form_for(@diagram) do |f| %>
  <% if @diagram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagram.errors.count, "error") %> prohibited this diagram from being saved:</h2>

      <ul>
      <% @diagram.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :legend %><br />
    <%= f.text_field :legend %>
  </div>
  <div class="field">
    <%= f.label :val %><br />
    <%= f.number_field :val %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagrams/edit.html.erb
<h1>Editing diagram</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagram %> |
<%= link_to 'Back', diagrams_path %>

app/views/diagrams/index.html.erb
<h1>Listing diagrams</h1>

<table>
  <tr>
    <th>Legend</th>
    <th>Val</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diagrams.each do |diagram| %>
  <tr>
    <td><%= diagram.legend %></td>
    <td><%= diagram.val %></td>
    <td><%= link_to 'Show', diagram %></td>
    <td><%= link_to 'Edit', edit_diagram_path(diagram) %></td>
    <td><%= link_to 'Destroy', diagram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diagram', new_diagram_path %>

<hr>

Total: <%= get_total(@diagrams) %>


<hr>
<img src="<%= get_diagram_url(@diagrams,"Opinion") %>"/>

<hr>
<img src="<%= get_diagram_url_pie(@diagrams,"Opinion") %>"/>
<hr>
<img alt="get_diagram_url_horbar" src="<%= get_diagram_url_horbar(@diagrams,"Opinion") %>"/>
<hr>
<hr>

app/views/diagrams/new.html.erb
<h1>New diagram</h1>

<%= render 'form' %>

<%= link_to 'Back', diagrams_path %>

app/views/diagrams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Legend:</b>
  <%= @diagram.legend %>
</p>

<p>
  <b>Val:</b>
  <%= @diagram.val %>
</p>


<%= link_to 'Edit', edit_diagram_path(@diagram) %> |
<%= link_to 'Back', diagrams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Citrusgraph</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>